"""Validate and deterministically sync the canonical equipment command profile to Godot."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any, cast

from jsonschema import Draft202012Validator  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "protocol/equipment-command-profile-v1.json"
SCHEMA = ROOT / "protocol/equipment-command-profile-v1.schema.json"
DESTINATION = ROOT / "godot/client/resources/protocol/equipment-command-profile-v1.json"
HASH_DESTINATION = ROOT / "godot/client/scripts/equipment_command_profile_hash.gd"


def canonical_bytes() -> bytes:
    payload = cast(dict[str, Any], json.loads(SOURCE.read_text(encoding="utf-8")))
    schema = cast(dict[str, Any], json.loads(SCHEMA.read_text(encoding="utf-8")))
    Draft202012Validator.check_schema(schema)
    Draft202012Validator(schema).validate(payload)
    return (json.dumps(payload, indent=2, ensure_ascii=False) + "\n").encode()


def hash_script(profile_bytes: bytes) -> bytes:
    digest = hashlib.sha256(profile_bytes).hexdigest()
    return (
        "# Generated by backend/scripts/sync_equipment_command_profile.py.\n"
        "class_name EquipmentCommandProfileHash\n"
        "extends RefCounted\n\n"
        f'const SHA256 := "{digest}"\n'
    ).encode()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = canonical_bytes()
    expected_hash_script = hash_script(expected)
    if args.check:
        if (
            not DESTINATION.is_file()
            or DESTINATION.read_bytes() != expected
            or not HASH_DESTINATION.is_file()
            or HASH_DESTINATION.read_bytes() != expected_hash_script
        ):
            raise SystemExit("Godot equipment command profile is not synchronized")
        return 0
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_bytes(expected)
    HASH_DESTINATION.write_bytes(expected_hash_script)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
