# Generated by backend/scripts/sync_equipment_command_profile.py.
class_name EquipmentCommandProfileHash
extends RefCounted

const SHA256 := "5057dcba49feb5c31ccbaa0e99bc3b50d03655f643203b5a5177ed0358535034"
